// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBBgftVQFuBdz6Nugp6OrCV1eyETBW2Iw0",
    authDomain: "pediagua-23bbc.firebaseapp.com",
    projectId: "pediagua-23bbc",
    storageBucket: "pediagua-23bbc.appspot.com",
    messagingSenderId: "235648758214",
    appId: "1:235648758214:web:b54d5d6c76a91a0acc42c7",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBBgftVQFuBdz6Nugp6OrCV1eyETBW2Iw0",
    authDomain: "pediagua-23bbc.firebaseapp.com",
    projectId: "pediagua-23bbc",
    storageBucket: "pediagua-23bbc.appspot.com",
    messagingSenderId: "235648758214",
    appId: "1:235648758214:web:b54d5d6c76a91a0acc42c7",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBBgftVQFuBdz6Nugp6OrCV1eyETBW2Iw0",
    authDomain: "pediagua-23bbc.firebaseapp.com",
    projectId: "pediagua-23bbc",
    storageBucket: "pediagua-23bbc.appspot.com",
    messagingSenderId: "235648758214",
    appId: "1:235648758214:web:b54d5d6c76a91a0acc42c7",
  );
}